package proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

public final class ChatOuterClass
{
    private ChatOuterClass()
    {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry)
    {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry)
    {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ChatLogOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ChatLog)
            com.google.protobuf.MessageOrBuilder
    {

        /**
         * <code>string message = 1;</code>
         */
        String getMessage();

        /**
         * <code>string message = 1;</code>
         */
        com.google.protobuf.ByteString
        getMessageBytes();

        /**
         * <code>string name = 2;</code>
         */
        String getName();

        /**
         * <code>string name = 2;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>.google.protobuf.Timestamp time = 3;</code>
         */
        boolean hasTime();

        /**
         * <code>.google.protobuf.Timestamp time = 3;</code>
         */
        com.google.protobuf.Timestamp getTime();

        /**
         * <code>.google.protobuf.Timestamp time = 3;</code>
         */
        com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();
    }

    /**
     * Protobuf type {@code ChatLog}
     */
    public static final class ChatLog extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ChatLog)
            ChatLogOrBuilder
    {
        private static final long serialVersionUID = 0L;

        // Use ChatLog.newBuilder() to construct.
        private ChatLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder)
        {
            super(builder);
        }

        private ChatLog()
        {
            message_ = "";
            name_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields()
        {
            return this.unknownFields;
        }

        private ChatLog(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            this();
            if (extensionRegistry == null)
            {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try
            {
                boolean done = false;
                while (!done)
                {
                    int tag = input.readTag();
                    switch (tag)
                    {
                        case 0:
                            done = true;
                            break;
                        case 10:
                        {
                            String s = input.readStringRequireUtf8();

                            message_ = s;
                            break;
                        }
                        case 18:
                        {
                            String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 26:
                        {
                            com.google.protobuf.Timestamp.Builder subBuilder = null;
                            if (time_ != null)
                            {
                                subBuilder = time_.toBuilder();
                            }
                            time_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
                            if (subBuilder != null)
                            {
                                subBuilder.mergeFrom(time_);
                                time_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default:
                        {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag))
                            {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e)
            {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e)
            {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally
            {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor()
        {
            return ChatOuterClass.internal_static_ChatLog_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable()
        {
            return ChatOuterClass.internal_static_ChatLog_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ChatLog.class, Builder.class);
        }

        public static final int MESSAGE_FIELD_NUMBER = 1;
        private volatile Object message_;

        /**
         * <code>string message = 1;</code>
         */
        public String getMessage()
        {
            Object ref = message_;
            if (ref instanceof String)
            {
                return (String) ref;
            } else
            {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                message_ = s;
                return s;
            }
        }

        /**
         * <code>string message = 1;</code>
         */
        public com.google.protobuf.ByteString
        getMessageBytes()
        {
            Object ref = message_;
            if (ref instanceof String)
            {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                message_ = b;
                return b;
            } else
            {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int NAME_FIELD_NUMBER = 2;
        private volatile Object name_;

        /**
         * <code>string name = 2;</code>
         */
        public String getName()
        {
            Object ref = name_;
            if (ref instanceof String)
            {
                return (String) ref;
            } else
            {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes()
        {
            Object ref = name_;
            if (ref instanceof String)
            {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                name_ = b;
                return b;
            } else
            {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TIME_FIELD_NUMBER = 3;
        private com.google.protobuf.Timestamp time_;

        /**
         * <code>.google.protobuf.Timestamp time = 3;</code>
         */
        public boolean hasTime()
        {
            return time_ != null;
        }

        /**
         * <code>.google.protobuf.Timestamp time = 3;</code>
         */
        public com.google.protobuf.Timestamp getTime()
        {
            return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        }

        /**
         * <code>.google.protobuf.Timestamp time = 3;</code>
         */
        public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder()
        {
            return getTime();
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized()
        {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException
        {
            if (!getMessageBytes().isEmpty())
            {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
            }
            if (!getNameBytes().isEmpty())
            {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            if (time_ != null)
            {
                output.writeMessage(3, getTime());
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize()
        {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getMessageBytes().isEmpty())
            {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
            }
            if (!getNameBytes().isEmpty())
            {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            if (time_ != null)
            {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, getTime());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj)
        {
            if (obj == this)
            {
                return true;
            }
            if (!(obj instanceof ChatLog))
            {
                return super.equals(obj);
            }
            ChatLog other = (ChatLog) obj;

            boolean result = true;
            result = result && getMessage()
                    .equals(other.getMessage());
            result = result && getName()
                    .equals(other.getName());
            result = result && (hasTime() == other.hasTime());
            if (hasTime())
            {
                result = result && getTime()
                        .equals(other.getTime());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode()
        {
            if (memoizedHashCode != 0)
            {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getMessage().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            if (hasTime())
            {
                hash = (37 * hash) + TIME_FIELD_NUMBER;
                hash = (53 * hash) + getTime().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static ChatLog parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static ChatLog parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ChatLog parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static ChatLog parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ChatLog parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static ChatLog parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ChatLog parseFrom(java.io.InputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ChatLog parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ChatLog parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static ChatLog parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ChatLog parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ChatLog parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType()
        {
            return newBuilder();
        }

        public static Builder newBuilder()
        {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ChatLog prototype)
        {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder()
        {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent)
        {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code ChatLog}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ChatLog)
                ChatLogOrBuilder
        {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor()
            {
                return ChatOuterClass.internal_static_ChatLog_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable()
            {
                return ChatOuterClass.internal_static_ChatLog_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ChatLog.class, Builder.class);
            }

            // Construct using proto.ChatOuterClass.ChatLog.newBuilder()
            private Builder()
            {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent)
            {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization()
            {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders)
                {
                }
            }

            @Override
            public Builder clear()
            {
                super.clear();
                message_ = "";

                name_ = "";

                if (timeBuilder_ == null)
                {
                    time_ = null;
                } else
                {
                    time_ = null;
                    timeBuilder_ = null;
                }
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType()
            {
                return ChatOuterClass.internal_static_ChatLog_descriptor;
            }

            @Override
            public ChatLog getDefaultInstanceForType()
            {
                return ChatLog.getDefaultInstance();
            }

            @Override
            public ChatLog build()
            {
                ChatLog result = buildPartial();
                if (!result.isInitialized())
                {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public ChatLog buildPartial()
            {
                ChatLog result = new ChatLog(this);
                result.message_ = message_;
                result.name_ = name_;
                if (timeBuilder_ == null)
                {
                    result.time_ = time_;
                } else
                {
                    result.time_ = timeBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @Override
            public Builder clone()
            {
                return (Builder) super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value)
            {
                return (Builder) super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field)
            {
                return (Builder) super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof)
            {
                return (Builder) super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value)
            {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value)
            {
                return (Builder) super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other)
            {
                if (other instanceof ChatLog)
                {
                    return mergeFrom((ChatLog) other);
                } else
                {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ChatLog other)
            {
                if (other == ChatLog.getDefaultInstance()) return this;
                if (!other.getMessage().isEmpty())
                {
                    message_ = other.message_;
                    onChanged();
                }
                if (!other.getName().isEmpty())
                {
                    name_ = other.name_;
                    onChanged();
                }
                if (other.hasTime())
                {
                    mergeTime(other.getTime());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized()
            {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException
            {
                ChatLog parsedMessage = null;
                try
                {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e)
                {
                    parsedMessage = (ChatLog) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally
                {
                    if (parsedMessage != null)
                    {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object message_ = "";

            /**
             * <code>string message = 1;</code>
             */
            public String getMessage()
            {
                Object ref = message_;
                if (!(ref instanceof String))
                {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    message_ = s;
                    return s;
                } else
                {
                    return (String) ref;
                }
            }

            /**
             * <code>string message = 1;</code>
             */
            public com.google.protobuf.ByteString
            getMessageBytes()
            {
                Object ref = message_;
                if (ref instanceof String)
                {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    message_ = b;
                    return b;
                } else
                {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string message = 1;</code>
             */
            public Builder setMessage(
                    String value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }

                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string message = 1;</code>
             */
            public Builder clearMessage()
            {

                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            /**
             * <code>string message = 1;</code>
             */
            public Builder setMessageBytes(
                    com.google.protobuf.ByteString value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                message_ = value;
                onChanged();
                return this;
            }

            private Object name_ = "";

            /**
             * <code>string name = 2;</code>
             */
            public String getName()
            {
                Object ref = name_;
                if (!(ref instanceof String))
                {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else
                {
                    return (String) ref;
                }
            }

            /**
             * <code>string name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes()
            {
                Object ref = name_;
                if (ref instanceof String)
                {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    name_ = b;
                    return b;
                } else
                {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 2;</code>
             */
            public Builder setName(
                    String value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 2;</code>
             */
            public Builder clearName()
            {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string name = 2;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.Timestamp time_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeBuilder_;

            /**
             * <code>.google.protobuf.Timestamp time = 3;</code>
             */
            public boolean hasTime()
            {
                return timeBuilder_ != null || time_ != null;
            }

            /**
             * <code>.google.protobuf.Timestamp time = 3;</code>
             */
            public com.google.protobuf.Timestamp getTime()
            {
                if (timeBuilder_ == null)
                {
                    return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
                } else
                {
                    return timeBuilder_.getMessage();
                }
            }

            /**
             * <code>.google.protobuf.Timestamp time = 3;</code>
             */
            public Builder setTime(com.google.protobuf.Timestamp value)
            {
                if (timeBuilder_ == null)
                {
                    if (value == null)
                    {
                        throw new NullPointerException();
                    }
                    time_ = value;
                    onChanged();
                } else
                {
                    timeBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Timestamp time = 3;</code>
             */
            public Builder setTime(
                    com.google.protobuf.Timestamp.Builder builderForValue)
            {
                if (timeBuilder_ == null)
                {
                    time_ = builderForValue.build();
                    onChanged();
                } else
                {
                    timeBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Timestamp time = 3;</code>
             */
            public Builder mergeTime(com.google.protobuf.Timestamp value)
            {
                if (timeBuilder_ == null)
                {
                    if (time_ != null)
                    {
                        time_ =
                                com.google.protobuf.Timestamp.newBuilder(time_).mergeFrom(value).buildPartial();
                    } else
                    {
                        time_ = value;
                    }
                    onChanged();
                } else
                {
                    timeBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Timestamp time = 3;</code>
             */
            public Builder clearTime()
            {
                if (timeBuilder_ == null)
                {
                    time_ = null;
                    onChanged();
                } else
                {
                    time_ = null;
                    timeBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Timestamp time = 3;</code>
             */
            public com.google.protobuf.Timestamp.Builder getTimeBuilder()
            {

                onChanged();
                return getTimeFieldBuilder().getBuilder();
            }

            /**
             * <code>.google.protobuf.Timestamp time = 3;</code>
             */
            public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder()
            {
                if (timeBuilder_ != null)
                {
                    return timeBuilder_.getMessageOrBuilder();
                } else
                {
                    return time_ == null ?
                            com.google.protobuf.Timestamp.getDefaultInstance() : time_;
                }
            }

            /**
             * <code>.google.protobuf.Timestamp time = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
            getTimeFieldBuilder()
            {
                if (timeBuilder_ == null)
                {
                    timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                            getTime(),
                            getParentForChildren(),
                            isClean());
                    time_ = null;
                }
                return timeBuilder_;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields)
            {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields)
            {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ChatLog)
        }

        // @@protoc_insertion_point(class_scope:ChatLog)
        private static final ChatLog DEFAULT_INSTANCE;

        static
        {
            DEFAULT_INSTANCE = new ChatLog();
        }

        public static ChatLog getDefaultInstance()
        {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ChatLog>
                PARSER = new com.google.protobuf.AbstractParser<ChatLog>()
        {
            @Override
            public ChatLog parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                return new ChatLog(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ChatLog> parser()
        {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<ChatLog> getParserForType()
        {
            return PARSER;
        }

        @Override
        public ChatLog getDefaultInstanceForType()
        {
            return DEFAULT_INSTANCE;
        }

    }

    public interface UserOrBuilder extends
            // @@protoc_insertion_point(interface_extends:User)
            com.google.protobuf.MessageOrBuilder
    {

        /**
         * <code>string name = 1;</code>
         */
        String getName();

        /**
         * <code>string name = 1;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();
    }

    /**
     * Protobuf type {@code User}
     */
    public static final class User extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:User)
            UserOrBuilder
    {
        private static final long serialVersionUID = 0L;

        // Use User.newBuilder() to construct.
        private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder)
        {
            super(builder);
        }

        private User()
        {
            name_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields()
        {
            return this.unknownFields;
        }

        private User(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            this();
            if (extensionRegistry == null)
            {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try
            {
                boolean done = false;
                while (!done)
                {
                    int tag = input.readTag();
                    switch (tag)
                    {
                        case 0:
                            done = true;
                            break;
                        case 10:
                        {
                            String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        default:
                        {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag))
                            {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e)
            {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e)
            {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally
            {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor()
        {
            return ChatOuterClass.internal_static_User_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable()
        {
            return ChatOuterClass.internal_static_User_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            User.class, Builder.class);
        }

        public static final int NAME_FIELD_NUMBER = 1;
        private volatile Object name_;

        /**
         * <code>string name = 1;</code>
         */
        public String getName()
        {
            Object ref = name_;
            if (ref instanceof String)
            {
                return (String) ref;
            } else
            {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes()
        {
            Object ref = name_;
            if (ref instanceof String)
            {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                name_ = b;
                return b;
            } else
            {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized()
        {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException
        {
            if (!getNameBytes().isEmpty())
            {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize()
        {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getNameBytes().isEmpty())
            {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj)
        {
            if (obj == this)
            {
                return true;
            }
            if (!(obj instanceof User))
            {
                return super.equals(obj);
            }
            User other = (User) obj;

            boolean result = true;
            result = result && getName()
                    .equals(other.getName());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode()
        {
            if (memoizedHashCode != 0)
            {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static User parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static User parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static User parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static User parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static User parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static User parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static User parseFrom(java.io.InputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static User parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static User parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static User parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static User parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static User parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType()
        {
            return newBuilder();
        }

        public static Builder newBuilder()
        {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(User prototype)
        {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder()
        {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent)
        {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code User}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:User)
                UserOrBuilder
        {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor()
            {
                return ChatOuterClass.internal_static_User_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable()
            {
                return ChatOuterClass.internal_static_User_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                User.class, Builder.class);
            }

            // Construct using proto.ChatOuterClass.User.newBuilder()
            private Builder()
            {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent)
            {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization()
            {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders)
                {
                }
            }

            @Override
            public Builder clear()
            {
                super.clear();
                name_ = "";

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType()
            {
                return ChatOuterClass.internal_static_User_descriptor;
            }

            @Override
            public User getDefaultInstanceForType()
            {
                return User.getDefaultInstance();
            }

            @Override
            public User build()
            {
                User result = buildPartial();
                if (!result.isInitialized())
                {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public User buildPartial()
            {
                User result = new User(this);
                result.name_ = name_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone()
            {
                return (Builder) super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value)
            {
                return (Builder) super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field)
            {
                return (Builder) super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof)
            {
                return (Builder) super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value)
            {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value)
            {
                return (Builder) super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other)
            {
                if (other instanceof User)
                {
                    return mergeFrom((User) other);
                } else
                {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(User other)
            {
                if (other == User.getDefaultInstance()) return this;
                if (!other.getName().isEmpty())
                {
                    name_ = other.name_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized()
            {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException
            {
                User parsedMessage = null;
                try
                {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e)
                {
                    parsedMessage = (User) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally
                {
                    if (parsedMessage != null)
                    {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object name_ = "";

            /**
             * <code>string name = 1;</code>
             */
            public String getName()
            {
                Object ref = name_;
                if (!(ref instanceof String))
                {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else
                {
                    return (String) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes()
            {
                Object ref = name_;
                if (ref instanceof String)
                {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    name_ = b;
                    return b;
                } else
                {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             *
             * @return
             */
            public Builder setName(
                    String value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             */
            public Builder clearName()
            {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields)
            {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields)
            {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:User)
        }

        // @@protoc_insertion_point(class_scope:User)
        private static final User DEFAULT_INSTANCE;

        static
        {
            DEFAULT_INSTANCE = new User();
        }

        public static User getDefaultInstance()
        {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<User>
                PARSER = new com.google.protobuf.AbstractParser<User>()
        {
            @Override
            public User parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                return new User(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<User> parser()
        {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<User> getParserForType()
        {
            return PARSER;
        }

        @Override
        public User getDefaultInstanceForType()
        {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ChatLog_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ChatLog_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_User_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_User_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor()
    {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static
    {
        String[] descriptorData = {
                "\n\nchat.proto\032\033google/protobuf/empty.prot" +
                        "o\032\037google/protobuf/timestamp.proto\"R\n\007Ch" +
                        "atLog\022\017\n\007message\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022(\n\004" +
                        "time\030\003 \001(\0132\032.google.protobuf.Timestamp\"\024" +
                        "\n\004User\022\014\n\004name\030\001 \001(\t2\216\001\n\004Chat\022+\n\005Write\022\010" +
                        ".ChatLog\032\026.google.protobuf.Empty\"\000\022/\n\tSu" +
                        "bscribe\022\026.google.protobuf.Empty\032\010.ChatLo" +
                        "g\"\000\022(\n\005LogIn\022\005.User\032\026.google.protobuf.Em" +
                        "pty\"\000b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner()
                {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root)
                    {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.EmptyProto.getDescriptor(),
                                com.google.protobuf.TimestampProto.getDescriptor(),
                        }, assigner);
        internal_static_ChatLog_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_ChatLog_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ChatLog_descriptor,
                new String[]{"Message", "Name", "Time",});
        internal_static_User_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_User_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_User_descriptor,
                new String[]{"Name",});
        com.google.protobuf.EmptyProto.getDescriptor();
        com.google.protobuf.TimestampProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
